import type { PitchClaim } from "./types";

export const pitchClaims: PitchClaim[] = [
  {
    id: "claim-kisanai-positioning",
    claim: "KisanAI is publicly positioned as an AI-powered agricultural assistant.",
    value: "Public site title and founder materials",
    sourceIds: ["kisanai-site", "founder-reddit"],
    confidence: "high",
    label: "verified",
    category: "Technical feasibility proof",
    useInPitch: "Use as product identity proof, while avoiding unsupported 'India's first' claims.",
  },
  {
    id: "claim-product-scope",
    claim: "KisanAI's intended feature set includes regional-language Q&A, crop image triage, mandi prices, weather, and schemes.",
    value: "Founder public description",
    sourceIds: ["founder-reddit"],
    confidence: "high",
    label: "verified",
    category: "Technical feasibility proof",
    useInPitch: "Use in product section to explain the current wedge.",
  },
  {
    id: "claim-stack",
    claim: "The public founder note describes a modern web and AI stack.",
    value: "Next.js, Cloudflare Workers, PostgreSQL, multilingual model pipeline",
    sourceIds: ["founder-reddit"],
    confidence: "high",
    label: "verified",
    category: "Technical feasibility proof",
    useInPitch: "Use as build credibility, not as proof of production hardening.",
  },
  {
    id: "claim-traction-gap",
    claim: "The supplied files do not establish public traction, paid pilots, revenue, or retention.",
    value: "No verified DAU, MAU, revenue, retention, partnerships, or outcomes",
    sourceIds: ["internal-assumptions"],
    confidence: "high",
    label: "risk",
    category: "Risk proof",
    useInPitch: "Use as honesty badge and risk section anchor.",
  },
  {
    id: "claim-kisan-kapas-docs",
    claim: "Farmers face confusion in digital agricultural workflows.",
    value: "Farmers reportedly could not understand required registration documents",
    sourceIds: ["toi-kisan-kapas"],
    confidence: "medium",
    label: "verified",
    category: "Agriculture pain proof",
    useInPitch: "Use to show digitization alone is not enough.",
  },
  {
    id: "claim-kisan-kapas-blank",
    claim: "Broken agricultural app flows can destroy trust.",
    value: "APMC section reportedly blank",
    sourceIds: ["toi-kisan-kapas"],
    confidence: "medium",
    label: "verified",
    category: "Agriculture pain proof",
    useInPitch: "Use in problem and safety sections.",
  },
  {
    id: "claim-procurement-failures",
    claim: "Failed digital procurement workflows can create real offline cost.",
    value: "Farmers reportedly made repeated trips and were pushed toward private traders",
    sourceIds: ["toi-andhra-procurement"],
    confidence: "medium",
    label: "verified",
    category: "Agriculture pain proof",
    useInPitch: "Use to connect UX failure with farmer economics.",
  },
  {
    id: "claim-onion-losses",
    claim: "Weather and disease shocks can create severe farmer distress.",
    value: "Onion farmers reported debt after heavy rain and disease losses",
    sourceIds: ["toi-onion-losses"],
    confidence: "medium",
    label: "verified",
    category: "Agriculture pain proof",
    useInPitch: "Use to justify disease/weather trigger moments.",
  },
  {
    id: "claim-onion-acre-spend",
    claim: "Crop decisions have meaningful money at stake.",
    value: "One onion grower cited about Rs 80,000 per acre spend",
    sourceIds: ["toi-onion-losses"],
    confidence: "medium",
    label: "verified",
    category: "Agriculture pain proof",
    useInPitch: "Use carefully to show downside versus advisory cost.",
  },
  {
    id: "claim-bharat-vistaar",
    claim: "Government interest validates multilingual AI farm advisory as a serious category.",
    value: "Bharat-VISTAAR launched as a multilingual AI tool for farm advisories",
    sourceIds: ["toi-bharat-vistaar"],
    confidence: "medium",
    label: "verified",
    category: "Policy proof",
    useInPitch: "Use in Why Now and government pilot sections.",
  },
  {
    id: "claim-farmrise",
    claim: "Farmer-facing digital agriculture products can reach large adoption in India.",
    value: "FarmRise crossed 5 million users",
    sourceIds: ["et-farmrise"],
    confidence: "medium",
    label: "verified",
    category: "Digital adoption proof",
    useInPitch: "Use as category adoption proof, not KisanAI traction.",
  },
  {
    id: "claim-pm-kisan",
    claim: "PM-KISAN provides a large farmer beneficiary scale anchor.",
    value: "About 9.7 crore farmers cited for an instalment",
    sourceIds: ["pm-kisan-toi"],
    confidence: "medium",
    label: "verified",
    category: "Market proof",
    useInPitch: "Use as a planning anchor, not direct paid-user count.",
  },
  {
    id: "claim-tam",
    claim: "The supplied market model estimates a conservative software TAM from PM-KISAN scale.",
    value: "97,000,000 farmers x Rs 600/year = Rs 58.2 billion",
    sourceIds: ["pm-kisan-toi", "internal-assumptions"],
    confidence: "low",
    label: "assumption",
    category: "Assumption",
    useInPitch: "Use with explicit assumption badge and warning.",
  },
  {
    id: "claim-sam",
    claim: "The supplied model applies a reachability discount.",
    value: "45% reachable = 43.65 million farmers; Rs 26.19 billion/year",
    sourceIds: ["internal-assumptions"],
    confidence: "low",
    label: "assumption",
    category: "Assumption",
    useInPitch: "Use to show disciplined addressability logic.",
  },
  {
    id: "claim-som",
    claim: "The supplied model uses a narrow year-three SOM.",
    value: "0.5% of SAM = 218,250 covered farmers; Rs 130.95 million/year",
    sourceIds: ["internal-assumptions"],
    confidence: "low",
    label: "assumption",
    category: "Assumption",
    useInPitch: "Use as a scenario, not a forecast.",
  },
  {
    id: "claim-cropin",
    claim: "Data-led advisory can create measurable farm value in enterprise deployments.",
    value: "Reuters reported profit improvement in Cropin-linked deployments",
    sourceIds: ["reuters-cropin"],
    confidence: "high",
    label: "verified",
    category: "Commercial proof",
    useInPitch: "Use as external proof that data-driven advisory can matter.",
  },
  {
    id: "claim-plantix",
    claim: "Plant disease apps validate demand but also show accuracy and trust challenges.",
    value: "Plantix is a major crop diagnosis competitor; disease apps still need improvement",
    sourceIds: ["plantix-wiki", "wired-plantix", "arxiv-disease-apps"],
    confidence: "medium",
    label: "verified",
    category: "Commercial proof",
    useInPitch: "Use in competition and safety.",
  },
  {
    id: "claim-dehaat",
    claim: "Full-stack agri platforms validate the broader category but are not the same wedge.",
    value: "DeHaat is a scaled agri services benchmark",
    sourceIds: ["dehaat-wiki"],
    confidence: "medium",
    label: "verified",
    category: "Commercial proof",
    useInPitch: "Use in competition without claiming KisanAI matches scale.",
  },
  {
    id: "claim-rag-feasibility",
    claim: "Agricultural AI systems benefit from multilingual retrieval, curated corpora, and interaction design.",
    value: "Research supports RAG, multilingual QA, and safety/evaluation design",
    sourceIds: ["arxiv-agri-qa", "arxiv-aiep"],
    confidence: "medium",
    label: "verified",
    category: "Technical feasibility proof",
    useInPitch: "Use to explain why KisanAI is more than a chatbot.",
  },
  {
    id: "claim-dpdp",
    claim: "KisanAI must treat privacy, consent, retention, and image/location processing as product requirements.",
    value: "DPDP framework is relevant to user data in India",
    sourceIds: ["dpdp-wiki"],
    confidence: "medium",
    label: "to-validate",
    category: "Policy proof",
    useInPitch: "Use as compliance posture; do not claim full legal compliance.",
  },
  {
    id: "claim-b2b2c",
    claim: "The strongest early revenue path is partner-led B2B2C, not broad direct subscription.",
    value: "FPO/NGO/government/agri partner pilots first",
    sourceIds: ["internal-assumptions"],
    confidence: "low",
    label: "assumption",
    category: "Assumption",
    useInPitch: "Use as GTM plan and investor-risk mitigation.",
  },
  {
    id: "claim-upi-gap",
    claim: "The supplied files do not support UPI-specific farmer monetization claims.",
    value: "No direct UPI agriculture adoption proof in supplied files",
    sourceIds: ["internal-assumptions"],
    confidence: "high",
    label: "risk",
    category: "Risk proof",
    useInPitch: "Avoid unsupported payment/adoption claims.",
  },
];

export const claimById = Object.fromEntries(
  pitchClaims.map((claim) => [claim.id, claim]),
) as Record<string, PitchClaim>;

