import type { PitchQA } from "./types";

export const investorQuestions: PitchQA[] = [
  {
    id: "qa-001",
    category: "Basic",
    difficulty: "Basic",
    confidence: "High proof",
    question: "What is KisanAI?",
    whyInvestorAsks: "They need the category in one clean sentence before details.",
    shortAnswer: "KisanAI is a vernacular AI farming assistant for daily agricultural decisions.",
    detailedAnswer: "KisanAI helps farmers and agri institutions answer recurring questions across disease triage, weather action, mandi context, and scheme guidance. The pitch should frame it as decision support, not a generic chatbot or full farm super-app.",
    proof: "The public founder note describes regional-language answers, image-based crop disease detection, mandi prices, weather, and schemes.",
    sourceIds: ["founder-reddit", "kisanai-site"],
    whatNotToSay: "KisanAI is India's first guaranteed farming AI for every farmer.",
    bestFounderAnswer: "KisanAI is a vernacular decision-support layer for Indian agriculture, starting with the moments when farmers need a safe next step quickly.",
    suggestedReference: "Hero; Executive Snapshot",
  },
  {
    id: "qa-002",
    category: "Basic",
    difficulty: "Basic",
    confidence: "Medium proof",
    question: "Who is the first user?",
    whyInvestorAsks: "They are checking whether the founder is focused or saying 'all farmers'.",
    shortAnswer: "The first user should be a farmer or farmer-family decision helper in a focused crop cluster.",
    detailedAnswer: "The research argues against starting with all India. The stronger wedge is one crop, one geography, one language, and one partner channel where product quality, onboarding, and feedback can be controlled.",
    proof: "This is a strategic recommendation from the supplied research, not observed KisanAI usage data.",
    sourceIds: ["internal-assumptions"],
    whatNotToSay: "Every Indian farmer is our immediate user.",
    bestFounderAnswer: "We start narrow: one crop cluster, one region, one language, and a partner-assisted cohort. That is how we learn trust and repeat use before scaling.",
    suggestedReference: "Executive Snapshot; GTM",
  },
  {
    id: "qa-003",
    category: "Basic",
    difficulty: "Basic",
    confidence: "Assumption",
    question: "Who pays first?",
    whyInvestorAsks: "They want to know whether revenue depends on low-income farmers paying immediately.",
    shortAnswer: "The strongest early payer is a partner: FPO, NGO, government pilot, CSR program, or agri institution.",
    detailedAnswer: "Direct farmer monetization should be tested after trust and retention. Partner-led pilots can concentrate usage, reduce CAC, and produce dashboards and measurable outcomes that justify contracts.",
    proof: "B2B2C is a recommended model from the research and is not yet validated KisanAI revenue.",
    sourceIds: ["internal-assumptions"],
    whatNotToSay: "Farmers will definitely pay from day one.",
    bestFounderAnswer: "We plan to prove value through partner-led pilots first, then test farmer premium only after the habit loop is visible.",
    suggestedReference: "Business Model",
  },
  {
    id: "qa-004",
    category: "Basic",
    difficulty: "Good",
    confidence: "Medium proof",
    question: "What problem does KisanAI solve?",
    whyInvestorAsks: "They need to see urgency, not just a feature list.",
    shortAnswer: "It reduces decision friction when farmers need timely, trusted, local-language guidance.",
    detailedAnswer: "The problem is not lack of information. It is that the right information is often fragmented, late, hard to understand, or not trusted enough to act on. KisanAI turns disease, weather, price, and scheme context into usable next steps.",
    proof: "The research cites app confusion, blank sections, repeated office trips, procurement failure, and crop-loss distress.",
    sourceIds: ["toi-kisan-kapas", "toi-andhra-procurement", "toi-onion-losses"],
    whatNotToSay: "Farmers have no information today.",
    bestFounderAnswer: "Farmers have information, but not always usable information at the decision moment. We make the next step clearer, safer, and source-backed.",
    suggestedReference: "The Problem",
  },
  {
    id: "qa-005",
    category: "Basic",
    difficulty: "Good",
    confidence: "High proof",
    question: "What is the wedge?",
    whyInvestorAsks: "They want to know what KisanAI will become best at first.",
    shortAnswer: "The wedge is the 'what should I do today?' loop.",
    detailedAnswer: "KisanAI should begin with high-frequency or high-stakes trigger moments: a crop symptom, weather event, mandi visit, or scheme deadline. That is narrower and more memorable than claiming the full farm operating system on day one.",
    proof: "The product scope is supported by founder materials; the wedge is a strategy derived from the research.",
    sourceIds: ["founder-reddit", "internal-assumptions"],
    whatNotToSay: "We are building everything for agriculture.",
    bestFounderAnswer: "We start with disease triage, weather-to-action, mandi context, and scheme navigation because these are repeated decision moments.",
    suggestedReference: "KisanAI Product",
  },
  {
    id: "qa-006",
    category: "Basic",
    difficulty: "Basic",
    confidence: "Needs validation",
    question: "What traction exists today?",
    whyInvestorAsks: "They are separating a shipped prototype from a validated company.",
    shortAnswer: "The supplied files do not prove public traction, revenue, retention, or partnerships.",
    detailedAnswer: "The pitch should be explicit: KisanAI is pilot-ready and early-stage. It should not claim users, paid pilots, government partnerships, revenue, or outcomes until they are documented.",
    proof: "The source analysis found no verified DAU, MAU, retention, revenue, signed pilots, or outcomes.",
    sourceIds: ["internal-assumptions"],
    whatNotToSay: "We have massive traction but cannot disclose it.",
    bestFounderAnswer: "We are not claiming fake traction. The next proof is a measured 90-day pilot with engagement, quality, and partner-conversion metrics.",
    suggestedReference: "Hero; Risks & Mitigations",
  },
  {
    id: "qa-007",
    category: "Market",
    difficulty: "Good",
    confidence: "Medium proof",
    question: "How large is the market?",
    whyInvestorAsks: "They want to see a large outcome without inflated math.",
    shortAnswer: "Large, but the page should use a conservative planning model rather than treating all farmers as paid users.",
    detailedAnswer: "The supplied model starts from about 9.7 crore PM-KISAN-linked farmers, applies a reachability discount, and uses Rs 600 per farmer per year. This creates a TAM of Rs 58.2B, but it must be labeled assumption-led.",
    proof: "PM-KISAN scale is sourced; Rs 600/year and 45% reachability are assumptions.",
    sourceIds: ["pm-kisan-toi", "internal-assumptions"],
    whatNotToSay: "Our TAM is the entire Indian agriculture GDP.",
    bestFounderAnswer: "We anchor on identifiable farmer scale, discount for reachability, and model only software-relevant value.",
    suggestedReference: "Market Opportunity",
  },
  {
    id: "qa-008",
    category: "Market",
    difficulty: "Good",
    confidence: "Assumption",
    question: "What are TAM, SAM, and SOM?",
    whyInvestorAsks: "They want explicit math and assumptions.",
    shortAnswer: "TAM is Rs 58.2B, SAM is Rs 26.19B, and year-three SOM is Rs 130.95M in the supplied planning model.",
    detailedAnswer: "The model uses 97M farmers at Rs 600/year, then applies 45% reachability and 0.5% SOM capture. This is a planning model for discussion, not an audited forecast or evidence of KisanAI demand.",
    proof: "Derived from PM-KISAN scale plus internal assumptions in the research files.",
    sourceIds: ["pm-kisan-toi", "internal-assumptions"],
    whatNotToSay: "Every PM-KISAN farmer is a buyer.",
    bestFounderAnswer: "We show the math and the discounts so investors can challenge the assumptions instead of trusting a vanity TAM.",
    suggestedReference: "Market Opportunity",
  },
  {
    id: "qa-009",
    category: "Market",
    difficulty: "Tough",
    confidence: "Medium proof",
    question: "Are Indian farmers digitally reachable enough?",
    whyInvestorAsks: "Rural adoption is the central skepticism.",
    shortAnswer: "Yes, but reachability is not the same as adoption.",
    detailedAnswer: "FarmRise crossing 5 million users proves farmer-facing agri apps can scale, and PM-KISAN shows large digital farmer rails. KisanAI still should use mobile-first, partner-assisted distribution because trust and local workflow fit matter more than raw access.",
    proof: "FarmRise and PM-KISAN are sourced; KisanAI adoption remains to validate.",
    sourceIds: ["et-farmrise", "pm-kisan-toi"],
    whatNotToSay: "Smartphone access means everyone will use us.",
    bestFounderAnswer: "Digital reach is real, but adoption is earned. We start with partner-assisted cohorts and measure repeat usage.",
    suggestedReference: "Why Now; GTM",
  },
  {
    id: "qa-010",
    category: "Market",
    difficulty: "Good",
    confidence: "Medium proof",
    question: "Is agriculture big enough for VC-scale outcomes?",
    whyInvestorAsks: "They are testing whether this is an impact project or venture-scale company.",
    shortAnswer: "It can be, if KisanAI becomes infrastructure for repeated decisions and partner workflows.",
    detailedAnswer: "A direct farmer app alone may be hard. The larger path combines B2B2C advisory, partner SaaS, dashboards, enterprise/API, and future embedded services after trust is built.",
    proof: "Scaled category benchmarks include FarmRise, DeHaat, Plantix, and Cropin; KisanAI scale is unproven.",
    sourceIds: ["et-farmrise", "dehaat-wiki", "plantix-wiki", "reuters-cropin"],
    whatNotToSay: "Agriculture is huge, therefore we are huge.",
    bestFounderAnswer: "The market is large, but the investable path is repeated decision infrastructure with partner-led distribution.",
    suggestedReference: "Business Model; Technical Moat",
  },
  {
    id: "qa-011",
    category: "Market",
    difficulty: "Tough",
    confidence: "Medium proof",
    question: "How will climate volatility affect demand?",
    whyInvestorAsks: "They want to know whether demand is structural or seasonal noise.",
    shortAnswer: "Climate and weather volatility increase the need for timely advisory, but KisanAI should not overclaim climate outcomes.",
    detailedAnswer: "Weather and disease shocks create recurring trigger moments. The product should convert weather into action while measuring engagement and reported usefulness, not claim yield protection before controlled evidence.",
    proof: "The onion loss reporting shows severe weather/disease downside; Cropin reporting shows data-led advisory can create value.",
    sourceIds: ["toi-onion-losses", "reuters-cropin"],
    whatNotToSay: "We will prevent climate losses.",
    bestFounderAnswer: "We help farmers respond faster and with better context; impact claims require pilot evidence.",
    suggestedReference: "The Problem; Roadmap",
  },
  {
    id: "qa-012",
    category: "Market",
    difficulty: "Good",
    confidence: "Medium proof",
    question: "What market proof exists outside KisanAI?",
    whyInvestorAsks: "They want category validation without relying on founder optimism.",
    shortAnswer: "FarmRise, Cropin, Plantix, DeHaat, eNAM, and Bharat-VISTAAR validate pieces of the category.",
    detailedAnswer: "The market already has digital farmer apps, government market infrastructure, enterprise agronomy, and AI advisory activity. That proves demand and competition. KisanAI's opening is not category creation; it is workflow simplicity and trust.",
    proof: "Sources include Economic Times, Reuters, government/platform overviews, and competitor references.",
    sourceIds: ["et-farmrise", "reuters-cropin", "plantix-wiki", "dehaat-wiki", "enam-wiki", "toi-bharat-vistaar"],
    whatNotToSay: "There is no competition.",
    bestFounderAnswer: "Incumbents prove demand. We focus on the lightweight trusted decision layer they do not fully own.",
    suggestedReference: "Competition",
  },
  {
    id: "qa-013",
    category: "Farmer Adoption",
    difficulty: "Tough",
    confidence: "Assumption",
    question: "Why will farmers trust AI?",
    whyInvestorAsks: "Trust is the hardest adoption barrier.",
    shortAnswer: "They will trust it only if the product behaves responsibly and proves usefulness in real moments.",
    detailedAnswer: "Trust comes from local language, useful first answers, source/freshness labels, clear uncertainty, and escalation. KisanAI should not expect trust from the word AI; it must earn trust through behavior and partner distribution.",
    proof: "The research cites broken app experiences as trust failures and recommends source-grounded safety.",
    sourceIds: ["toi-kisan-kapas", "arxiv-aiep", "arxiv-agri-qa"],
    whatNotToSay: "Farmers will trust us because AI is advanced.",
    bestFounderAnswer: "We design for trust: local language, no overclaiming, visible sources, and escalation when the answer is uncertain.",
    suggestedReference: "AI Safety & Trust",
  },
  {
    id: "qa-014",
    category: "Farmer Adoption",
    difficulty: "Good",
    confidence: "Assumption",
    question: "What is the aha moment?",
    whyInvestorAsks: "They want to know the first repeatable value moment.",
    shortAnswer: "Send a crop photo or urgent question and get a safe, local next step.",
    detailedAnswer: "The strongest aha is not a long dashboard. It is a farmer asking in their language during a real trigger moment and getting an answer that is understandable, cautious, and actionable.",
    proof: "This is a product hypothesis tied to the disease/weather/mandi/scheme wedge.",
    sourceIds: ["founder-reddit", "internal-assumptions"],
    whatNotToSay: "The chatbot itself is the aha.",
    bestFounderAnswer: "The aha is clarity at the decision moment: what it might be, what to do next, when to seek expert help, and which source supports it.",
    suggestedReference: "KisanAI Product",
  },
  {
    id: "qa-015",
    category: "Farmer Adoption",
    difficulty: "Tough",
    confidence: "Needs validation",
    question: "What if farmers use it only once?",
    whyInvestorAsks: "They are testing whether this is novelty or habit.",
    shortAnswer: "That is a core pilot risk, and it must be measured.",
    detailedAnswer: "KisanAI should track day-7 and day-30 retention by trigger type. If farmers return around weather events, disease symptoms, mandi days, or scheme deadlines, the wedge is working. If not, the product or channel is wrong.",
    proof: "No public KisanAI retention data exists in supplied files.",
    sourceIds: ["internal-assumptions"],
    whatNotToSay: "Retention will be high because agriculture is daily.",
    bestFounderAnswer: "We do not assume retention. We instrument it and use pilots to learn which workflows create repeat behavior.",
    suggestedReference: "Government / FPO Pilot Proposal",
  },
  {
    id: "qa-016",
    category: "Farmer Adoption",
    difficulty: "Trick",
    confidence: "Needs validation",
    question: "Can children operate it for farmers?",
    whyInvestorAsks: "They are probing household-assisted digital use and literacy assumptions.",
    shortAnswer: "Possibly in some households, but KisanAI should not rely on or claim this without pilot evidence.",
    detailedAnswer: "The safer design principle is family-assisted use, not child-dependent use. The product should work with low typing burden, voice/image input, local language, and assisted onboarding.",
    proof: "The supplied research explicitly warns not to bluff household usage patterns.",
    sourceIds: ["internal-assumptions"],
    whatNotToSay: "Children in every village will operate it for their parents.",
    bestFounderAnswer: "We design for family-assisted use, but we will validate actual household behavior in pilots instead of assuming it.",
    suggestedReference: "Investor Q&A; Risks & Mitigations",
  },
  {
    id: "qa-017",
    category: "Farmer Adoption",
    difficulty: "Good",
    confidence: "Assumption",
    question: "Why WhatsApp or PWA first?",
    whyInvestorAsks: "They want practical distribution rather than app-store fantasy.",
    shortAnswer: "Messaging and mobile web reduce install friction and match existing behavior.",
    detailedAnswer: "App-store growth is expensive and diffuse. Partner-assisted WhatsApp/PWA flows can meet farmers where they already ask questions and allow field staff to onboard cohorts.",
    proof: "Messaging-first distribution is a strategic recommendation from the research files.",
    sourceIds: ["internal-assumptions", "founder-reddit"],
    whatNotToSay: "Native app downloads will grow organically.",
    bestFounderAnswer: "We start where farmers and field teams already communicate, then add deeper app surfaces after usage is proven.",
    suggestedReference: "GTM",
  },
  {
    id: "qa-018",
    category: "Farmer Adoption",
    difficulty: "Tough",
    confidence: "Assumption",
    question: "What if farmers prefer dealers and WhatsApp groups?",
    whyInvestorAsks: "They know local trust networks are strong.",
    shortAnswer: "KisanAI should fit into those workflows rather than trying to erase them.",
    detailedAnswer: "Dealers and groups are substitutes and channels. KisanAI can provide a source-backed second opinion, shareable advisory cards, and escalation paths while partners use their existing trust to onboard users.",
    proof: "The research frames human networks as existing substitutes and partner channels.",
    sourceIds: ["internal-assumptions"],
    whatNotToSay: "We will replace all local advice networks.",
    bestFounderAnswer: "We become the trusted decision layer inside existing channels, not a behavior change tax.",
    suggestedReference: "Competition; GTM",
  },
  {
    id: "qa-019",
    category: "Product",
    difficulty: "Tough",
    confidence: "Assumption",
    question: "Is this just a chatbot wrapper?",
    whyInvestorAsks: "They are probing defensibility beyond an LLM API.",
    shortAnswer: "No. The LLM is one layer inside a decision workflow.",
    detailedAnswer: "KisanAI's defensibility must come from context capture, source retrieval, live data connectors, local language UX, safety controls, partner dashboards, and feedback loops. The base model is replaceable.",
    proof: "Research supports retrieval-backed agricultural QA and the need for curated corpora and interaction design.",
    sourceIds: ["arxiv-agri-qa", "arxiv-aiep", "internal-assumptions"],
    whatNotToSay: "Our model is better than everyone else's.",
    bestFounderAnswer: "We are not building a generic chat UI. We are building agriculture decision infrastructure around source-grounding, workflow, distribution, and safety.",
    suggestedReference: "How It Works; Technical Moat",
  },
  {
    id: "qa-020",
    category: "Product",
    difficulty: "Good",
    confidence: "High proof",
    question: "Why disease triage?",
    whyInvestorAsks: "They want a strong wedge, not random modules.",
    shortAnswer: "Disease symptoms are urgent, visual, repeated, and economically meaningful.",
    detailedAnswer: "A visible crop symptom creates immediate uncertainty and possible input spend. KisanAI should frame outputs as possible issues, confidence, caution, and next steps, not definitive diagnosis.",
    proof: "Crop image detection is in the founder note; disease app research shows both demand and the need for caution.",
    sourceIds: ["founder-reddit", "arxiv-disease-apps"],
    whatNotToSay: "We can diagnose every disease accurately now.",
    bestFounderAnswer: "Disease triage is a first-response workflow. We reduce uncertainty and escalate when confidence is low.",
    suggestedReference: "KisanAI Product; AI Safety & Trust",
  },
  {
    id: "qa-021",
    category: "Product",
    difficulty: "Good",
    confidence: "Medium proof",
    question: "Why weather advisory?",
    whyInvestorAsks: "They want to know how this differs from weather apps.",
    shortAnswer: "Farmers need weather-to-action, not raw forecast display.",
    detailedAnswer: "The value is translating forecast context into crop-stage actions, warnings, and reminders. KisanAI should show freshness and avoid pretending it can control weather risk.",
    proof: "Weather is in the founder feature set; crop loss reporting supports urgency.",
    sourceIds: ["founder-reddit", "toi-onion-losses"],
    whatNotToSay: "We will predict weather better than weather companies.",
    bestFounderAnswer: "We do not compete with weather data providers. We convert weather into farm actions in the farmer's language.",
    suggestedReference: "Product; How It Works",
  },
  {
    id: "qa-022",
    category: "Product",
    difficulty: "Good",
    confidence: "High proof",
    question: "Why mandi prices?",
    whyInvestorAsks: "They are checking whether this drives repeat use and economic value.",
    shortAnswer: "Mandi context supports selling decisions and reduces dependence on hearsay.",
    detailedAnswer: "Raw price data is not enough. Farmers need nearby context, freshness, trend, and plain-language explanation. KisanAI should avoid giving trading guarantees.",
    proof: "Mandi prices are in the public product direction; eNAM validates market-price infrastructure.",
    sourceIds: ["founder-reddit", "enam-wiki"],
    whatNotToSay: "We guarantee better sale prices.",
    bestFounderAnswer: "We help interpret price context and freshness so the farmer asks better questions before selling.",
    suggestedReference: "Product",
  },
  {
    id: "qa-023",
    category: "Product",
    difficulty: "Good",
    confidence: "Medium proof",
    question: "Why schemes?",
    whyInvestorAsks: "They want to know whether this is real utility or content clutter.",
    shortAnswer: "Scheme navigation is high-value when simplified safely.",
    detailedAnswer: "Farmers can lose time on eligibility, documents, and confusing portals. KisanAI should explain requirements and source links but never guarantee eligibility or approval.",
    proof: "Public research cited app documentation confusion and KisanAI's scheme-guidance feature direction.",
    sourceIds: ["toi-kisan-kapas", "founder-reddit"],
    whatNotToSay: "We will get every farmer every subsidy.",
    bestFounderAnswer: "We simplify scheme understanding and document checklists, while linking to official sources and avoiding approval guarantees.",
    suggestedReference: "Product; AI Safety & Trust",
  },
  {
    id: "qa-024",
    category: "Product",
    difficulty: "Tough",
    confidence: "Needs validation",
    question: "What happens if the AI is wrong?",
    whyInvestorAsks: "They are probing liability, trust, and safety design.",
    shortAnswer: "The system must reduce risk through source-grounding, uncertainty, escalation, and auditability.",
    detailedAnswer: "Wrong answers cannot be eliminated, so KisanAI should classify risk, avoid definitive claims, show sources, escalate uncertain cases, and log outputs for review. High-risk pesticide, disease, finance, and legal guidance needs stricter controls.",
    proof: "Research recommends retrieval, abstention, evaluation, and escalation.",
    sourceIds: ["arxiv-aiep", "arxiv-agri-qa", "arxiv-disease-apps"],
    whatNotToSay: "The model will not be wrong.",
    bestFounderAnswer: "We assume mistakes are possible and design controls around that reality.",
    suggestedReference: "AI Safety & Trust; Risks & Mitigations",
  },
  {
    id: "qa-025",
    category: "Product",
    difficulty: "Tough",
    confidence: "Assumption",
    question: "Is the product too broad?",
    whyInvestorAsks: "They see disease, weather, prices, schemes, marketplace, and worry about focus.",
    shortAnswer: "The public product direction is broad; the pitch narrows it to a first wedge.",
    detailedAnswer: "KisanAI should not execute every module nationally at once. The pitch should show a narrow MVP and expansion logic: disease, weather, mandi, and schemes in one cohort first, then scale after retention.",
    proof: "The source analysis explicitly warns against all-agriculture-for-all-India positioning.",
    sourceIds: ["internal-assumptions", "founder-reddit"],
    whatNotToSay: "We will launch every feature everywhere immediately.",
    bestFounderAnswer: "The vision is broad, but execution starts narrow and measured.",
    suggestedReference: "Roadmap",
  },
  {
    id: "qa-026",
    category: "Product",
    difficulty: "Good",
    confidence: "Assumption",
    question: "What is the partner dashboard for?",
    whyInvestorAsks: "They want the B2B buyer value proposition.",
    shortAnswer: "It gives partners visibility into farmer questions, escalations, engagement, and pilot outcomes.",
    detailedAnswer: "FPOs, NGOs, and government pilots need reporting, not just an app link. A dashboard turns farmer usage into measurable program outputs and makes annual contract conversion more plausible.",
    proof: "Dashboard value is a strategic recommendation from the supplied research.",
    sourceIds: ["internal-assumptions"],
    whatNotToSay: "The dashboard is a nice admin extra.",
    bestFounderAnswer: "The dashboard is what makes KisanAI buyable by institutions: support, analytics, escalation, and proof.",
    suggestedReference: "Government / FPO Pilot Proposal",
  },
  {
    id: "qa-027",
    category: "AI Safety",
    difficulty: "Tough",
    confidence: "Medium proof",
    question: "How do you reduce hallucination?",
    whyInvestorAsks: "Agricultural advice can cause real harm.",
    shortAnswer: "Use retrieval, source restrictions, risk classification, abstention, and evaluation.",
    detailedAnswer: "KisanAI should route queries, retrieve from curated sources, attach citations, classify high-risk tasks, ask clarifying questions, and abstain or escalate when confidence is low. Safety is product infrastructure, not a disclaimer.",
    proof: "Agricultural AI research supports curated corpora, RAG, and multi-turn interaction design.",
    sourceIds: ["arxiv-agri-qa", "arxiv-aiep"],
    whatNotToSay: "Prompt engineering solves hallucination.",
    bestFounderAnswer: "We use layered controls: source-grounding, risk routing, answer constraints, evaluation, and escalation.",
    suggestedReference: "AI Safety & Trust; How It Works",
  },
  {
    id: "qa-028",
    category: "AI Safety",
    difficulty: "Tough",
    confidence: "Medium proof",
    question: "Do you give pesticide or dosage recommendations?",
    whyInvestorAsks: "This is a high-liability area.",
    shortAnswer: "Only with verified source support and cautious framing; otherwise escalate.",
    detailedAnswer: "The product should avoid unsupported chemical or dosage advice. Where guidance is sourced, it should include label/official-source caveats and expert escalation. Disease triage should say possible issue, not final diagnosis.",
    proof: "Disease app research and the source analysis emphasize caution and expert escalation.",
    sourceIds: ["arxiv-disease-apps", "internal-assumptions"],
    whatNotToSay: "The AI can prescribe treatment safely in all cases.",
    bestFounderAnswer: "We are conservative with chemical guidance and treat high-risk recommendations as source-required and escalation-ready.",
    suggestedReference: "AI Safety & Trust",
  },
  {
    id: "qa-029",
    category: "AI Safety",
    difficulty: "Good",
    confidence: "Medium proof",
    question: "How do citations work?",
    whyInvestorAsks: "They want proof that source-grounding is visible to users.",
    shortAnswer: "Every factual answer should display source or freshness where available.",
    detailedAnswer: "For schemes, mandi, weather, and agronomy, the answer should include source title, freshness timestamp where relevant, and confidence. If no reliable source exists, the answer should say so.",
    proof: "The pitch source model and RAG research support citation-aware outputs.",
    sourceIds: ["arxiv-agri-qa", "arxiv-aiep"],
    whatNotToSay: "Sources are hidden in the backend.",
    bestFounderAnswer: "The farmer and partner both see why an answer should be trusted or when it should not be treated as final.",
    suggestedReference: "Data Proof Room",
  },
  {
    id: "qa-030",
    category: "AI Safety",
    difficulty: "Tough",
    confidence: "Needs validation",
    question: "What are your accuracy metrics?",
    whyInvestorAsks: "They want evidence, not safety intent.",
    shortAnswer: "Public accuracy metrics are not established in the supplied files.",
    detailedAnswer: "KisanAI should measure grounded-answer rate, false-advice rate, abstention quality, diagnosis top-k accuracy, language adequacy, and helpfulness. These should be pilot outputs before strong claims are made.",
    proof: "No public KisanAI accuracy data exists in the supplied files.",
    sourceIds: ["internal-assumptions", "arxiv-disease-apps"],
    whatNotToSay: "Our AI is highly accurate without testing.",
    bestFounderAnswer: "We do not claim production accuracy yet. We define the metrics and use pilots to produce evidence.",
    suggestedReference: "Government / FPO Pilot Proposal; Roadmap",
  },
  {
    id: "qa-031",
    category: "AI Safety",
    difficulty: "Good",
    confidence: "Medium proof",
    question: "How do you handle privacy?",
    whyInvestorAsks: "The product may process phone numbers, images, crop, and location data.",
    shortAnswer: "KisanAI needs consent, minimization, retention controls, deletion, security, and audit logs.",
    detailedAnswer: "The pitch should show DPDP awareness without claiming legal compliance unless implemented. Image and location consent should be separate and plain-language.",
    proof: "The research identifies DPDP as relevant to KisanAI's expected data types.",
    sourceIds: ["dpdp-wiki", "internal-assumptions"],
    whatNotToSay: "Privacy is not important because this is agriculture.",
    bestFounderAnswer: "Privacy is part of trust. We minimize data, ask consent, define retention, and audit partner deployments.",
    suggestedReference: "AI Safety & Trust",
  },
  {
    id: "qa-032",
    category: "AI Safety",
    difficulty: "Good",
    confidence: "Assumption",
    question: "How do you handle outdated data?",
    whyInvestorAsks: "Mandi, weather, and schemes can age quickly.",
    shortAnswer: "Show freshness labels and avoid unsupported certainty.",
    detailedAnswer: "Live or time-sensitive data should include timestamp, source, and caveat. If freshness is unknown, KisanAI should label it and avoid firm recommendations.",
    proof: "This is a safety requirement derived from source analysis.",
    sourceIds: ["internal-assumptions"],
    whatNotToSay: "All data is always live.",
    bestFounderAnswer: "Freshness is visible in the answer. If data is stale or uncertain, we say so.",
    suggestedReference: "AI Safety & Trust",
  },
  {
    id: "qa-033",
    category: "Business Model",
    difficulty: "Good",
    confidence: "Assumption",
    question: "What is the first revenue stream?",
    whyInvestorAsks: "They need a path from pilot to cash.",
    shortAnswer: "Paid pilots or partner contracts are the first realistic revenue stream.",
    detailedAnswer: "The first buyer can be an FPO, NGO, CSR program, district pilot, or agri partner that pays for covered farmers, dashboard visibility, and support automation.",
    proof: "This is the recommended business model sequence in the supplied research.",
    sourceIds: ["internal-assumptions"],
    whatNotToSay: "Revenue will come from ads or generic subscriptions immediately.",
    bestFounderAnswer: "The first revenue comes from institutions that already aggregate farmers and need measurable advisory workflows.",
    suggestedReference: "Business Model",
  },
  {
    id: "qa-034",
    category: "Business Model",
    difficulty: "Tough",
    confidence: "Assumption",
    question: "Will farmers pay?",
    whyInvestorAsks: "They are skeptical of B2C rural subscription revenue.",
    shortAnswer: "Some may, but farmer premium should be tested after trust and retention.",
    detailedAnswer: "The safer early plan is partner-led contracts. Farmer premium can work for expert escalation, alerts, and personalized planning, but should not be the sole first revenue hypothesis.",
    proof: "No KisanAI willingness-to-pay evidence exists in the supplied files.",
    sourceIds: ["internal-assumptions"],
    whatNotToSay: "Farmers will definitely pay Rs X per month.",
    bestFounderAnswer: "We treat direct farmer payment as a later experiment, not the foundation of the first pilot.",
    suggestedReference: "Financial Model & Unit Economics",
  },
  {
    id: "qa-035",
    category: "Business Model",
    difficulty: "Good",
    confidence: "Assumption",
    question: "Will government pay?",
    whyInvestorAsks: "Public-sector revenue can be attractive but slow.",
    shortAnswer: "Possibly, but only after pilot proof and procurement clarity.",
    detailedAnswer: "Government can be a strong pilot channel for scheme navigation, advisory reach, and reporting. KisanAI should not imply procurement success or partnership before evidence exists.",
    proof: "Bharat-VISTAAR validates category interest; KisanAI government revenue is not proven.",
    sourceIds: ["toi-bharat-vistaar", "internal-assumptions"],
    whatNotToSay: "Government will definitely buy this.",
    bestFounderAnswer: "We make government adoption easier through a 90-day measurable pilot with safety, privacy, and KPIs.",
    suggestedReference: "Government / FPO Pilot Proposal",
  },
  {
    id: "qa-036",
    category: "Business Model",
    difficulty: "Good",
    confidence: "Assumption",
    question: "Can this become a marketplace?",
    whyInvestorAsks: "They see commerce monetization but worry about trust.",
    shortAnswer: "Yes later, but marketplace should follow trust, not lead it.",
    detailedAnswer: "Commerce can monetize input intent, soil testing, services, and referrals, but advice neutrality must be protected. If recommendations look paid or biased, the core trust asset weakens.",
    proof: "Plantix and DeHaat show commerce adjacency; KisanAI-specific commerce is unvalidated.",
    sourceIds: ["plantix-wiki", "dehaat-wiki", "wired-plantix", "internal-assumptions"],
    whatNotToSay: "We will sell inputs directly from day one.",
    bestFounderAnswer: "Advisory earns trust first; commerce is optional and disclosed later.",
    suggestedReference: "Business Model; Competition",
  },
  {
    id: "qa-037",
    category: "Business Model",
    difficulty: "Tough",
    confidence: "Assumption",
    question: "What is the path to Rs 1 crore ARR?",
    whyInvestorAsks: "They want a near-term revenue milestone.",
    shortAnswer: "A realistic path is a small number of partner contracts plus paid pilots.",
    detailedAnswer: "At Rs 216 per covered farmer/year, roughly 46,300 covered farmers can imply Rs 1 crore ARR. This is a scenario, not forecast, and depends on partner conversion and renewal.",
    proof: "Uses supplied B2B2C unit-economics assumptions.",
    sourceIds: ["internal-assumptions"],
    whatNotToSay: "Rs 1 crore ARR will happen automatically after launch.",
    bestFounderAnswer: "The path is contract math: focused pilots, conversion to annual contracts, and dashboard value for partners.",
    suggestedReference: "Financial Model & Unit Economics",
  },
  {
    id: "qa-038",
    category: "Business Model",
    difficulty: "Tough",
    confidence: "Assumption",
    question: "What is the path to Rs 10 crore ARR?",
    whyInvestorAsks: "They want to see scaling mechanics.",
    shortAnswer: "It requires repeatable multi-state partner contracts or higher-ACV enterprise/API lines.",
    detailedAnswer: "Low-ticket covered-farmer pricing alone requires large coverage. The stronger path layers FPO/NGO/government cohorts with enterprise dashboards, white-label, and API contracts after quality is proven.",
    proof: "Scenario logic from supplied financial models.",
    sourceIds: ["internal-assumptions"],
    whatNotToSay: "We just need 1% of India.",
    bestFounderAnswer: "Rs 10 crore ARR needs repeatable contracts, not vanity user counts. We expand only after retention and partner renewal are proven.",
    suggestedReference: "Financial Model & Unit Economics",
  },
  {
    id: "qa-039",
    category: "Business Model",
    difficulty: "Good",
    confidence: "Assumption",
    question: "Can this become a fintech or insurance layer?",
    whyInvestorAsks: "They are testing expansion upside.",
    shortAnswer: "It is a possible future adjacency, not a day-one claim.",
    detailedAnswer: "Crop, risk, advisory, and interaction data may support lending or insurance partners later, but KisanAI should avoid regulated advice without partnerships, compliance, and proven data quality.",
    proof: "The supplied research identifies fintech/insurance as future expansion, not current proof.",
    sourceIds: ["internal-assumptions", "dpdp-wiki"],
    whatNotToSay: "We will become a lender soon.",
    bestFounderAnswer: "Fintech and insurance are downstream possibilities after trust, consent, data quality, and partner demand are proven.",
    suggestedReference: "Business Model; Roadmap",
  },
  {
    id: "qa-040",
    category: "GTM",
    difficulty: "Tough",
    confidence: "Assumption",
    question: "How will you acquire farmers?",
    whyInvestorAsks: "CAC and trust are make-or-break.",
    shortAnswer: "Through partner-led cohorts, assisted onboarding, and messaging-first workflows.",
    detailedAnswer: "KisanAI should acquire early users through FPOs, NGOs, KVK-linked events, agri-input retailers, and government/CSR pilots. Direct ads and app-store discovery should not be the core early motion.",
    proof: "GTM strategy is a research recommendation, not yet proven.",
    sourceIds: ["internal-assumptions"],
    whatNotToSay: "We will run ads to farmers across India.",
    bestFounderAnswer: "We acquire through trusted local aggregators first, then use shareable answers to support organic discovery.",
    suggestedReference: "Go-To-Market Strategy",
  },
  {
    id: "qa-041",
    category: "GTM",
    difficulty: "Good",
    confidence: "Assumption",
    question: "Why not direct-to-consumer first?",
    whyInvestorAsks: "They want to know whether the founder understands rural CAC.",
    shortAnswer: "Direct-to-consumer can be tested, but broad D2C first is higher risk.",
    detailedAnswer: "Trust, language, onboarding, and support are easier inside a partner cohort. B2B2C also produces dashboards and measurable outcomes that create buyer value.",
    proof: "This is GTM logic from the supplied research.",
    sourceIds: ["internal-assumptions"],
    whatNotToSay: "D2C is easy because everyone has smartphones.",
    bestFounderAnswer: "We start where trust and feedback already exist, then expand consumer surfaces after proof.",
    suggestedReference: "GTM",
  },
  {
    id: "qa-042",
    category: "GTM",
    difficulty: "Good",
    confidence: "Assumption",
    question: "How will FPOs help?",
    whyInvestorAsks: "They are checking if partners have real operational value.",
    shortAnswer: "FPOs can aggregate farmers, onboard cohorts, and use a dashboard to support members.",
    detailedAnswer: "FPOs give KisanAI concentrated usage and feedback. KisanAI gives FPOs standardized advisory, escalation, and member engagement visibility.",
    proof: "FPO distribution is a recommended channel; no KisanAI FPO partnership is proven.",
    sourceIds: ["internal-assumptions"],
    whatNotToSay: "Every FPO will distribute us for free.",
    bestFounderAnswer: "An FPO pilot is valuable when both sides get measurable outcomes: farmer usage and partner support visibility.",
    suggestedReference: "Government / FPO Pilot Proposal",
  },
  {
    id: "qa-043",
    category: "GTM",
    difficulty: "Good",
    confidence: "Assumption",
    question: "How will NGOs help?",
    whyInvestorAsks: "They want to know the non-profit/impact channel logic.",
    shortAnswer: "NGOs can deploy KisanAI inside livelihood, climate, and scheme-awareness programs.",
    detailedAnswer: "NGOs already have field relationships and reporting needs. KisanAI can reduce repetitive advisory burden and produce usage metrics for program reporting.",
    proof: "NGO distribution is a strategic recommendation, not a proven KisanAI channel.",
    sourceIds: ["internal-assumptions"],
    whatNotToSay: "NGOs will scale us without support.",
    bestFounderAnswer: "We use NGO pilots to learn trust, language, and field onboarding while creating measurable program outputs.",
    suggestedReference: "GTM; Pilot Proposal",
  },
  {
    id: "qa-044",
    category: "GTM",
    difficulty: "Tough",
    confidence: "Assumption",
    question: "How do you sell to government?",
    whyInvestorAsks: "Government sales are slow and relationship-heavy.",
    shortAnswer: "Start with a 90-day pilot proposal, not a national procurement claim.",
    detailedAnswer: "The government-ready pitch should define objectives, farmer cohort, crops, language, modules, dashboard, KPIs, safety, and expected outputs. After proof, procurement can be explored.",
    proof: "Bharat-VISTAAR validates interest; KisanAI government sales are not proven.",
    sourceIds: ["toi-bharat-vistaar", "internal-assumptions"],
    whatNotToSay: "We will sell to the government immediately at national scale.",
    bestFounderAnswer: "We ask for a small measurable pilot first, then let outcomes justify expansion.",
    suggestedReference: "Government / FPO Pilot Proposal",
  },
  {
    id: "qa-045",
    category: "GTM",
    difficulty: "Good",
    confidence: "Assumption",
    question: "How will you handle languages?",
    whyInvestorAsks: "India's language diversity can break generic products.",
    shortAnswer: "Start with one dominant regional language plus Hindi/English fallback.",
    detailedAnswer: "Adding too many languages early can dilute quality. KisanAI should validate one language-region-crop cluster, build evaluation data, then expand language coverage carefully.",
    proof: "The research recommends one primary regional language plus fallback.",
    sourceIds: ["internal-assumptions", "arxiv-agri-qa"],
    whatNotToSay: "We support every Indian language now.",
    bestFounderAnswer: "Language expansion follows quality proof, not ambition. We would rather be trusted in one language than vague in ten.",
    suggestedReference: "Roadmap",
  },
  {
    id: "qa-046",
    category: "Competition",
    difficulty: "Tough",
    confidence: "Medium proof",
    question: "Why won't DeHaat build this?",
    whyInvestorAsks: "Incumbents have distribution and resources.",
    shortAnswer: "They can build parts of it; KisanAI must win on focus, neutrality, and lightweight workflow fit.",
    detailedAnswer: "DeHaat validates the full-stack agri opportunity, but its operating model is broader. KisanAI should not claim incumbents cannot compete; it should build faster around the assistant-first decision layer.",
    proof: "DeHaat is a scaled category benchmark; KisanAI has no proven moat yet.",
    sourceIds: ["dehaat-wiki", "internal-assumptions"],
    whatNotToSay: "DeHaat is not a threat.",
    bestFounderAnswer: "Incumbents are real. Our job is to own a sharper, source-backed, partner-embeddable workflow before they do.",
    suggestedReference: "Competition; Technical Moat",
  },
  {
    id: "qa-047",
    category: "Competition",
    difficulty: "Tough",
    confidence: "Medium proof",
    question: "Why won't Plantix beat you on disease detection?",
    whyInvestorAsks: "Plantix has disease-diagnosis scale.",
    shortAnswer: "Plantix is strong in disease; KisanAI should not compete only as a disease app.",
    detailedAnswer: "KisanAI's wedge includes disease triage but expands into weather, market, scheme, partner dashboard, and safety workflows. It should also differentiate on neutrality and source transparency.",
    proof: "Plantix is a major crop diagnosis competitor; Wired and arXiv sources show trust and accuracy considerations.",
    sourceIds: ["plantix-wiki", "wired-plantix", "arxiv-disease-apps"],
    whatNotToSay: "Plantix is bad.",
    bestFounderAnswer: "Plantix proves demand. KisanAI's product is broader decision support and partner workflow, with disease as one trigger moment.",
    suggestedReference: "Competition",
  },
  {
    id: "qa-048",
    category: "Competition",
    difficulty: "Tough",
    confidence: "Medium proof",
    question: "Why won't Cropin build this?",
    whyInvestorAsks: "Cropin has enterprise agri data credibility.",
    shortAnswer: "Cropin is enterprise-first; KisanAI's first wedge is farmer-facing vernacular decision support.",
    detailedAnswer: "Cropin validates data-led advisory value. KisanAI should avoid competing head-on in enterprise analytics early and focus on lightweight partner-embedded farmer workflows.",
    proof: "Reuters reports Cropin-linked outcome stories.",
    sourceIds: ["reuters-cropin"],
    whatNotToSay: "Cropin is irrelevant.",
    bestFounderAnswer: "Cropin proves the value of data-led advisory; we start at the farmer interaction and partner workflow layer.",
    suggestedReference: "Competition",
  },
  {
    id: "qa-049",
    category: "Competition",
    difficulty: "Tough",
    confidence: "Medium proof",
    question: "Why won't the government build this?",
    whyInvestorAsks: "Government has scale and legitimacy.",
    shortAnswer: "Government can and is building advisory tools; KisanAI should be interoperable and pilot-friendly.",
    detailedAnswer: "Bharat-VISTAAR validates the category. KisanAI's opportunity is narrower local iteration, partner usability, dashboards, and deployment speed, not an anti-government posture.",
    proof: "Bharat-VISTAAR is a sourced category signal.",
    sourceIds: ["toi-bharat-vistaar"],
    whatNotToSay: "Government cannot build good products.",
    bestFounderAnswer: "We complement government systems by making advisories and schemes more usable in local workflows.",
    suggestedReference: "Government / FPO Pilot Proposal; Competition",
  },
  {
    id: "qa-050",
    category: "Competition",
    difficulty: "Trick",
    confidence: "Assumption",
    question: "Why won't ChatGPT or Gemini kill this?",
    whyInvestorAsks: "They are testing whether KisanAI has product depth beyond generic models.",
    shortAnswer: "Generic models do not solve distribution, source grounding, live data, local workflow, or trust by default.",
    detailedAnswer: "The model is replaceable. The defensibility is the workflow around it: farmer context, source corpus, live connectors, safety policy, partner dashboards, usage data, and local trust.",
    proof: "Research supports RAG and workflow design for agricultural QA; moat remains to be built.",
    sourceIds: ["arxiv-agri-qa", "arxiv-aiep", "internal-assumptions"],
    whatNotToSay: "Our AI model is smarter than ChatGPT.",
    bestFounderAnswer: "We use models as infrastructure; we build the agriculture-specific decision system around them.",
    suggestedReference: "Technical Moat",
  },
  {
    id: "qa-051",
    category: "Competition",
    difficulty: "Good",
    confidence: "Medium proof",
    question: "How do you position against FarmRise?",
    whyInvestorAsks: "FarmRise proves adoption and competitive pressure.",
    shortAnswer: "FarmRise validates farmer digital adoption; KisanAI must differentiate on assistant-first workflows and partner embedding.",
    detailedAnswer: "Bayer's scale is a strong signal. KisanAI should not claim better reach today; it should focus on source-backed, lightweight, local decision support with a clear safety posture.",
    proof: "Economic Times reports FarmRise crossed 5 million users.",
    sourceIds: ["et-farmrise"],
    whatNotToSay: "FarmRise users will all switch.",
    bestFounderAnswer: "FarmRise proves the user exists. We focus on a narrower workflow and partner-led validation.",
    suggestedReference: "Competition",
  },
  {
    id: "qa-052",
    category: "Financial",
    difficulty: "Good",
    confidence: "Assumption",
    question: "What are the expected gross margins?",
    whyInvestorAsks: "They want to know if AI costs break the model.",
    shortAnswer: "Software margins can be attractive, but support and field onboarding may dominate early cost.",
    detailedAnswer: "The research suggests AI inference can be manageable in lean usage scenarios. However, agronomy review, partner onboarding, safety operations, and support are likely more important cost drivers early.",
    proof: "Vendor pricing scenarios in the research are illustrative and should be re-verified.",
    sourceIds: ["openai-pricing", "cloudflare-r2-pricing", "neon-pricing", "internal-assumptions"],
    whatNotToSay: "AI costs are zero.",
    bestFounderAnswer: "Token cost is not the main risk. Distribution, support, trust, and expert review are the real economics to prove.",
    suggestedReference: "Financial Model & Unit Economics",
  },
  {
    id: "qa-053",
    category: "Financial",
    difficulty: "Tough",
    confidence: "Assumption",
    question: "What are your AI costs?",
    whyInvestorAsks: "They want to understand scalability and model dependence.",
    shortAnswer: "Illustrative models show low per-active-user AI cost is plausible, but actual costs need pilot measurement.",
    detailedAnswer: "Text-only, text-plus-image, and voice-heavy scenarios vary meaningfully. KisanAI should route low-risk queries to cheaper flows, cache repeated content, and limit expensive vision/voice calls.",
    proof: "The supplied research cites public vendor pricing but warns pricing changes.",
    sourceIds: ["openai-pricing", "cloudflare-r2-pricing", "neon-pricing", "pinecone-pricing", "vercel-pricing"],
    whatNotToSay: "We have exact unit costs without live usage.",
    bestFounderAnswer: "We model costs, but the pilot will measure real query mix, image use, and support load.",
    suggestedReference: "Financial Model & Unit Economics",
  },
  {
    id: "qa-054",
    category: "Financial",
    difficulty: "Tough",
    confidence: "Needs validation",
    question: "What is CAC?",
    whyInvestorAsks: "CAC determines whether low-ticket farmer revenue can work.",
    shortAnswer: "CAC is not publicly established and must be measured by channel.",
    detailedAnswer: "Partner-led CAC may be far lower than direct app-store growth, but it introduces sales and relationship costs. The pilot should track cost per activated farmer and partner-to-user conversion.",
    proof: "No KisanAI CAC data exists in supplied files.",
    sourceIds: ["internal-assumptions"],
    whatNotToSay: "CAC will be near zero because of word of mouth.",
    bestFounderAnswer: "We do not assume CAC. We measure it by channel and prioritize partner cohorts because they can reduce acquisition friction.",
    suggestedReference: "Pilot Proposal; Financials",
  },
  {
    id: "qa-055",
    category: "Financial",
    difficulty: "Tough",
    confidence: "Assumption",
    question: "What drives LTV?",
    whyInvestorAsks: "They want retention and revenue logic.",
    shortAnswer: "LTV is driven by partner renewal, covered-farmer pricing, repeat usage, and upsell to dashboards or expert workflows.",
    detailedAnswer: "For B2C, LTV requires retention and low CAC. For B2B2C, LTV depends on annual contract renewal and measurable partner value.",
    proof: "The unit economics are scenario models, not observed data.",
    sourceIds: ["internal-assumptions"],
    whatNotToSay: "LTV is high because agriculture is huge.",
    bestFounderAnswer: "LTV comes from repeated advisory usage and partner renewal, not market size slogans.",
    suggestedReference: "Financial Model & Unit Economics",
  },
  {
    id: "qa-056",
    category: "Technical Diligence",
    difficulty: "Good",
    confidence: "High proof",
    question: "What stack do you use?",
    whyInvestorAsks: "They want execution credibility and architecture clarity.",
    shortAnswer: "Public materials mention Next.js, Cloudflare Workers, PostgreSQL, and a multilingual model pipeline.",
    detailedAnswer: "That is a sensible MVP stack. The missing proof is not the stack name; it is retrieval quality, safety instrumentation, evaluation, and partner dashboard reliability.",
    proof: "Founder public note lists the stack.",
    sourceIds: ["founder-reddit"],
    whatNotToSay: "The stack itself is the moat.",
    bestFounderAnswer: "The stack lets us iterate quickly; the moat is the data, workflow, safety, and distribution layer.",
    suggestedReference: "Technical Moat",
  },
  {
    id: "qa-057",
    category: "Technical Diligence",
    difficulty: "Tough",
    confidence: "Medium proof",
    question: "RAG or fine-tuning?",
    whyInvestorAsks: "They want to know how facts stay current and grounded.",
    shortAnswer: "Start with RAG and structured routing; fine-tune later only if a stable dataset justifies it.",
    detailedAnswer: "Mandi, weather, and scheme data need freshness. A curated corpus with hybrid retrieval and live connectors is safer early than relying on model memory.",
    proof: "Agricultural QA research supports curated corpora and retrieval-backed systems.",
    sourceIds: ["arxiv-agri-qa", "arxiv-aiep"],
    whatNotToSay: "Fine-tuning solves all accuracy problems.",
    bestFounderAnswer: "We use retrieval for freshness and traceability, and consider fine-tuning only for stable language and workflow patterns.",
    suggestedReference: "How It Works",
  },
  {
    id: "qa-058",
    category: "Technical Diligence",
    difficulty: "Tough",
    confidence: "Assumption",
    question: "How do you handle low connectivity?",
    whyInvestorAsks: "Rural network quality affects adoption.",
    shortAnswer: "Use lightweight PWA/messaging flows, cached cards, short answers, and progressive upload behavior.",
    detailedAnswer: "The supplied research supports low-friction channels but does not prove KisanAI's offline capability. The product should minimize heavy UI, allow retry, and cache common guidance where safe.",
    proof: "Low-connectivity handling is a product requirement, not yet proven.",
    sourceIds: ["internal-assumptions"],
    whatNotToSay: "Connectivity is solved everywhere.",
    bestFounderAnswer: "We design for constrained mobile use and validate actual network behavior in pilot districts.",
    suggestedReference: "Product; Roadmap",
  },
  {
    id: "qa-059",
    category: "Technical Diligence",
    difficulty: "Good",
    confidence: "Assumption",
    question: "How do you handle voice?",
    whyInvestorAsks: "Voice can improve access but raise cost and error risk.",
    shortAnswer: "Voice is valuable but should be added where pilots show typing is a blocker.",
    detailedAnswer: "Voice should follow the same routing and safety system as text. It must handle language, noise, consent, cost, and transcription errors.",
    proof: "Voice is recommended as a future UX capability, not a proven current metric.",
    sourceIds: ["internal-assumptions"],
    whatNotToSay: "Voice will solve all literacy barriers.",
    bestFounderAnswer: "Voice is a serious roadmap item, but we will add it where it improves activation and retention in real cohorts.",
    suggestedReference: "Roadmap",
  },
  {
    id: "qa-060",
    category: "Technical Diligence",
    difficulty: "Tough",
    confidence: "Assumption",
    question: "How do you store farmer data?",
    whyInvestorAsks: "Data governance matters for partners and government.",
    shortAnswer: "The pitch should commit to minimization, consent, retention, deletion, access controls, and audit logs.",
    detailedAnswer: "Basic advisory should not require land records or identity documents. Uploaded images and location-like context should have explicit consent and retention rules.",
    proof: "DPDP relevance is sourced; implementation details need validation.",
    sourceIds: ["dpdp-wiki", "internal-assumptions"],
    whatNotToSay: "We store everything because data is the moat.",
    bestFounderAnswer: "We collect only what is needed for advisory and partner reporting, with clear consent and deletion paths.",
    suggestedReference: "AI Safety & Trust",
  },
  {
    id: "qa-061",
    category: "Technical Diligence",
    difficulty: "Advanced VC Diligence",
    confidence: "Assumption",
    question: "What data becomes proprietary?",
    whyInvestorAsks: "They want compounding advantage.",
    shortAnswer: "Crop-region-language interaction and feedback data can become proprietary if collected with consent and quality controls.",
    detailedAnswer: "The strongest proprietary asset is not public agronomy text. It is repeated farmer questions, images, clarifications, helpfulness, action taken, escalation outcomes, and partner cohort patterns.",
    proof: "This is a strategic moat hypothesis, not current proof.",
    sourceIds: ["internal-assumptions"],
    whatNotToSay: "All farmer data is ours to monetize.",
    bestFounderAnswer: "We build consented workflow data that improves local decision quality and partner reporting over time.",
    suggestedReference: "Technical Moat",
  },
  {
    id: "qa-062",
    category: "Government/Policy",
    difficulty: "Good",
    confidence: "Medium proof",
    question: "How does this fit government priorities?",
    whyInvestorAsks: "Public-sector fit affects pilot and grant potential.",
    shortAnswer: "It supports multilingual advisory, scheme navigation, and measurable farmer engagement.",
    detailedAnswer: "Bharat-VISTAAR validates government interest in AI farm advisories. KisanAI should position as an implementation and usability layer for localized pilots.",
    proof: "Bharat-VISTAAR is sourced; KisanAI government partnership is not.",
    sourceIds: ["toi-bharat-vistaar", "internal-assumptions"],
    whatNotToSay: "We are officially partnered with government.",
    bestFounderAnswer: "We align with digital agriculture goals by making advisories and schemes easier to use, while measuring outcomes.",
    suggestedReference: "Government / FPO Pilot Proposal",
  },
  {
    id: "qa-063",
    category: "Government/Policy",
    difficulty: "Tough",
    confidence: "Needs validation",
    question: "Do you have government partnerships?",
    whyInvestorAsks: "They are checking for fake logos or implied endorsement.",
    shortAnswer: "No government partnership is proven in the supplied files.",
    detailedAnswer: "The page should not show logos or imply official approval. It can present a government-ready pilot proposal and cite Bharat-VISTAAR only as category validation.",
    proof: "No signed KisanAI government partnership is present in supplied research.",
    sourceIds: ["internal-assumptions", "toi-bharat-vistaar"],
    whatNotToSay: "We are in talks with government, so it is basically done.",
    bestFounderAnswer: "We have a clear pilot proposal; partnership status will be claimed only after it is signed.",
    suggestedReference: "Government / FPO Pilot Proposal",
  },
  {
    id: "qa-064",
    category: "Government/Policy",
    difficulty: "Good",
    confidence: "Medium proof",
    question: "How do you handle DPDP?",
    whyInvestorAsks: "Government and enterprise partners care about privacy governance.",
    shortAnswer: "Design with DPDP awareness: consent, purpose limitation, minimization, deletion, security, and grievance process.",
    detailedAnswer: "KisanAI should say it is building a DPDP-aware posture, not claim legal compliance without counsel and implementation. Audit logs matter for institutional deployments.",
    proof: "DPDP relevance is sourced; legal compliance needs review.",
    sourceIds: ["dpdp-wiki", "internal-assumptions"],
    whatNotToSay: "We are compliant because we have a privacy page.",
    bestFounderAnswer: "We treat privacy as part of the trust architecture and will validate legal compliance before scale.",
    suggestedReference: "AI Safety & Trust",
  },
  {
    id: "qa-065",
    category: "Risk",
    difficulty: "Tough",
    confidence: "Needs validation",
    question: "What is the biggest risk?",
    whyInvestorAsks: "They want founder self-awareness.",
    shortAnswer: "Trust and repeat usage in a real farmer cohort.",
    detailedAnswer: "Model quality, source quality, partner distribution, retention, and support all converge into trust. If farmers do not return after the first trigger moment, the business does not work.",
    proof: "No public retention data exists; trust issues are visible in adjacent app failures.",
    sourceIds: ["internal-assumptions", "toi-kisan-kapas"],
    whatNotToSay: "There are no major risks.",
    bestFounderAnswer: "Our biggest risk is trust translating into repeat use. The pilot is designed to measure that directly.",
    suggestedReference: "Risks & Mitigations",
  },
  {
    id: "qa-066",
    category: "Risk",
    difficulty: "Tough",
    confidence: "Needs validation",
    question: "What if partners do not convert after pilots?",
    whyInvestorAsks: "Pilot enthusiasm often fails to become revenue.",
    shortAnswer: "Then KisanAI must revise buyer value, pricing, or channel.",
    detailedAnswer: "A good pilot should define conversion criteria upfront: active farmers, dashboard usage, support load reduction, answer helpfulness, and willingness to pay. If these are weak, do not scale the channel.",
    proof: "Partner conversion is not proven in supplied files.",
    sourceIds: ["internal-assumptions"],
    whatNotToSay: "Pilots always convert if users like the product.",
    bestFounderAnswer: "We design pilots to answer the conversion question, not just create demos.",
    suggestedReference: "Government / FPO Pilot Proposal",
  },
  {
    id: "qa-067",
    category: "Risk",
    difficulty: "Tough",
    confidence: "Assumption",
    question: "What if the product is too broad?",
    whyInvestorAsks: "They see scope creep risk.",
    shortAnswer: "KisanAI must use breadth as roadmap, not MVP.",
    detailedAnswer: "The focused pilot should choose one crop, one language, and a few decision modules. Marketplace, fintech, broad language coverage, and national expansion should wait.",
    proof: "The research repeatedly recommends narrowing scope.",
    sourceIds: ["internal-assumptions"],
    whatNotToSay: "Breadth is our advantage today.",
    bestFounderAnswer: "The vision is broad, but focus is the execution strategy.",
    suggestedReference: "Roadmap",
  },
  {
    id: "qa-068",
    category: "Risk",
    difficulty: "Good",
    confidence: "Assumption",
    question: "What if data sources are wrong?",
    whyInvestorAsks: "Source-grounded does not mean source-correct.",
    shortAnswer: "KisanAI needs source ranking, freshness, partner review, and error reporting.",
    detailedAnswer: "Official and reputable sources reduce risk but do not eliminate it. The system should capture source quality, date, geography, and user feedback, and allow rollback or correction.",
    proof: "This is part of the proposed safety architecture.",
    sourceIds: ["internal-assumptions", "arxiv-aiep"],
    whatNotToSay: "Sources make every answer correct.",
    bestFounderAnswer: "We manage source quality as an operational process with review and correction loops.",
    suggestedReference: "AI Safety & Trust",
  },
  {
    id: "qa-069",
    category: "Risk",
    difficulty: "Tough",
    confidence: "Needs validation",
    question: "What if CAC is high?",
    whyInvestorAsks: "Low-ARPA products cannot absorb high CAC.",
    shortAnswer: "That is why partner-led acquisition is the first GTM hypothesis.",
    detailedAnswer: "If partner CAC is still high or onboarding is too manual, KisanAI must increase ACV through dashboards, enterprise contracts, or narrow to more valuable workflows.",
    proof: "CAC is not yet proven.",
    sourceIds: ["internal-assumptions"],
    whatNotToSay: "CAC will be solved by virality.",
    bestFounderAnswer: "We track cost per activated farmer and partner conversion from the first pilot.",
    suggestedReference: "Financial Model & Unit Economics",
  },
  {
    id: "qa-070",
    category: "Trick/Irritating",
    difficulty: "Trick",
    confidence: "High proof",
    question: "Can KisanAI guarantee yield improvement?",
    whyInvestorAsks: "They are testing whether the founder overclaims.",
    shortAnswer: "No. KisanAI should not claim guaranteed yield improvement.",
    detailedAnswer: "The responsible claim is reducing decision friction and measuring outcomes during pilots. Yield impact can only be claimed after controlled evidence.",
    proof: "No yield impact data for KisanAI exists in the supplied files.",
    sourceIds: ["internal-assumptions"],
    whatNotToSay: "Yes, we guarantee higher yields.",
    bestFounderAnswer: "No. We help farmers access timely guidance and will measure outcome indicators before making yield claims.",
    suggestedReference: "Investor Q&A; Risks & Mitigations",
  },
  {
    id: "qa-071",
    category: "Trick/Irritating",
    difficulty: "Trick",
    confidence: "Needs validation",
    question: "Can you cover every crop immediately?",
    whyInvestorAsks: "They want to expose weak focus.",
    shortAnswer: "No, and trying would reduce quality.",
    detailedAnswer: "Crop coverage should expand only when the knowledge base, evaluation, and partner support exist for that crop-region context.",
    proof: "The research recommends one crop cluster first.",
    sourceIds: ["internal-assumptions"],
    whatNotToSay: "Yes, every crop is supported now.",
    bestFounderAnswer: "We start with selected crops where we can measure quality and usage, then expand deliberately.",
    suggestedReference: "Roadmap",
  },
  {
    id: "qa-072",
    category: "Trick/Irritating",
    difficulty: "Trick",
    confidence: "Needs validation",
    question: "Can you support every Indian language now?",
    whyInvestorAsks: "They are testing whether multilingual claims are shallow.",
    shortAnswer: "No. KisanAI should start with one primary regional language plus fallback.",
    detailedAnswer: "Language quality is safety and trust. Broad language claims without evaluation create risk, especially for scheme and disease advice.",
    proof: "The research recommends focused language rollout.",
    sourceIds: ["internal-assumptions", "arxiv-agri-qa"],
    whatNotToSay: "LLMs support every language, so we are done.",
    bestFounderAnswer: "We prioritize trustworthy language performance over broad but shallow coverage.",
    suggestedReference: "Roadmap; AI Safety & Trust",
  },
  {
    id: "qa-073",
    category: "Trick/Irritating",
    difficulty: "Irritating",
    confidence: "Assumption",
    question: "Why not build only a marketplace?",
    whyInvestorAsks: "They want to know if revenue is distracting the founder.",
    shortAnswer: "Marketplace economics depend on trust; advisory is the trust engine.",
    detailedAnswer: "Starting with commerce can bias recommendations and increase operational burden. KisanAI should earn trust through decision support before monetizing referrals or transactions.",
    proof: "Plantix and DeHaat show commerce adjacency but also highlight trust and operating complexity.",
    sourceIds: ["plantix-wiki", "dehaat-wiki", "wired-plantix", "internal-assumptions"],
    whatNotToSay: "Marketplace is easy money.",
    bestFounderAnswer: "Advisory first, commerce later if it is useful, disclosed, and trust-preserving.",
    suggestedReference: "Business Model",
  },
  {
    id: "qa-074",
    category: "Trick/Irritating",
    difficulty: "Irritating",
    confidence: "Assumption",
    question: "Why not build only a WhatsApp bot?",
    whyInvestorAsks: "They are checking product depth and distribution pragmatism.",
    shortAnswer: "Messaging can be an entry point, but the company needs workflow, safety, data, and partner tooling.",
    detailedAnswer: "A bot is a channel. The product is the decision-support system behind it: retrieval, source labels, escalation, analytics, and partner dashboards.",
    proof: "Founder materials include messaging orientation; the research recommends broader workflow architecture.",
    sourceIds: ["founder-reddit", "internal-assumptions"],
    whatNotToSay: "WhatsApp bot is the entire product.",
    bestFounderAnswer: "We use messaging for access, but the product is the agriculture decision infrastructure behind the conversation.",
    suggestedReference: "How It Works",
  },
  {
    id: "qa-075",
    category: "Trick/Irritating",
    difficulty: "Trick",
    confidence: "High proof",
    question: "Can you replace agronomists?",
    whyInvestorAsks: "They are testing safety posture.",
    shortAnswer: "No. KisanAI should triage and assist, not replace expert judgment.",
    detailedAnswer: "High-risk and uncertain cases should be escalated to local experts, KVKs, or partner field staff. The product can reduce repetitive burden, not remove human expertise.",
    proof: "The safety strategy in the research emphasizes escalation.",
    sourceIds: ["arxiv-disease-apps", "internal-assumptions"],
    whatNotToSay: "AI replaces agronomists entirely.",
    bestFounderAnswer: "We help agronomists and field teams focus on the hard cases by handling common questions safely.",
    suggestedReference: "AI Safety & Trust",
  },
  {
    id: "qa-076",
    category: "Trick/Irritating",
    difficulty: "Irritating",
    confidence: "Needs validation",
    question: "Can you become profitable in three months?",
    whyInvestorAsks: "They are pushing for unrealistic speed.",
    shortAnswer: "The responsible three-month goal is pilot proof, not forced profitability.",
    detailedAnswer: "A 90-day pilot should prove activation, retention, answer quality, support cost, and buyer value. Profitability comes after repeatable paid contracts and controlled operating cost.",
    proof: "No revenue or margin data exists in supplied files.",
    sourceIds: ["internal-assumptions"],
    whatNotToSay: "Yes, we will be profitable immediately.",
    bestFounderAnswer: "In three months we aim to prove a repeatable pilot-to-contract path, not pretend the business is mature.",
    suggestedReference: "Roadmap; Ask & Use of Funds",
  },
  {
    id: "qa-077",
    category: "Advanced VC Diligence",
    difficulty: "Advanced VC Diligence",
    confidence: "Needs validation",
    question: "What is the non-consensus insight?",
    whyInvestorAsks: "They want a venture insight, not just an impact story.",
    shortAnswer: "The winning product may be a decision layer inside existing agri workflows, not a standalone farmer super-app.",
    detailedAnswer: "The market already has apps, dealers, government systems, and WhatsApp groups. KisanAI can win by embedding trust, retrieval, and local-language guidance into those workflows instead of forcing a new behavior.",
    proof: "This is a strategic insight from the research, not a measured result.",
    sourceIds: ["internal-assumptions"],
    whatNotToSay: "The insight is that agriculture is big.",
    bestFounderAnswer: "Our insight is that trust and workflow fit matter more than app breadth in rural advisory.",
    suggestedReference: "Technical Moat; GTM",
  },
  {
    id: "qa-078",
    category: "Advanced VC Diligence",
    difficulty: "Advanced VC Diligence",
    confidence: "Needs validation",
    question: "What is the compounding loop?",
    whyInvestorAsks: "They want to see defensibility over time.",
    shortAnswer: "Better local answers drive usage, usage creates feedback, feedback improves quality, quality helps partners renew and expand.",
    detailedAnswer: "The loop compounds only if data is consented, labeled, reviewed, and tied to crop-region-language context. Without evaluation, more usage can create more risk rather than more moat.",
    proof: "This is a moat hypothesis to validate in pilots.",
    sourceIds: ["internal-assumptions"],
    whatNotToSay: "More data automatically creates moat.",
    bestFounderAnswer: "The compounding loop is quality-driven, not data-hoarding-driven.",
    suggestedReference: "Technical Moat",
  },
  {
    id: "qa-079",
    category: "Advanced VC Diligence",
    difficulty: "Advanced VC Diligence",
    confidence: "Needs validation",
    question: "What milestone unlocks the next round?",
    whyInvestorAsks: "They want fundraising discipline.",
    shortAnswer: "A measured pilot showing repeat usage, answer quality, partner value, and a credible paid conversion path.",
    detailedAnswer: "The next financing should be raised against evidence: active farmers in a cohort, day-7/day-30 retention, grounded-answer rate, escalation rate, partner dashboard use, and a signed or likely annual contract.",
    proof: "These are recommended KPIs from the research, not current metrics.",
    sourceIds: ["internal-assumptions"],
    whatNotToSay: "A prettier demo unlocks the round.",
    bestFounderAnswer: "The next round is unlocked by proof that the wedge repeats and buyers value it.",
    suggestedReference: "Pilot Proposal; Ask & Use of Funds",
  },
  {
    id: "qa-080",
    category: "Advanced VC Diligence",
    difficulty: "Advanced VC Diligence",
    confidence: "Needs validation",
    question: "What would make you shut down or pivot?",
    whyInvestorAsks: "They want intellectual honesty.",
    shortAnswer: "Low repeat use, unsafe answer quality, or partner non-conversion after focused pilots.",
    detailedAnswer: "If farmers do not return around trigger moments, if safety requires too much manual review at low price points, or if partners will not pay after clear outcomes, the wedge or channel must change.",
    proof: "No pilot data exists yet; these are rational kill criteria.",
    sourceIds: ["internal-assumptions"],
    whatNotToSay: "Nothing can stop us.",
    bestFounderAnswer: "We define failure conditions upfront so we learn quickly and avoid scaling a weak motion.",
    suggestedReference: "Risks & Mitigations",
  },
  {
    id: "qa-081",
    category: "Financial",
    difficulty: "Good",
    confidence: "Assumption",
    question: "What are you raising for?",
    whyInvestorAsks: "They want capital tied to proof, not vague buildout.",
    shortAnswer: "To prove repeatable pilot-to-contract conversion across focused crop/geography cohorts.",
    detailedAnswer: "Use of funds should cover product safety, agronomy review, corpus building, pilot deployment, field onboarding, dashboard, language UX, compliance, and partnerships. The amount remains a placeholder unless the founder sets a round.",
    proof: "Use-of-funds plan is strategic, not a committed financing round.",
    sourceIds: ["internal-assumptions"],
    whatNotToSay: "We need money to do everything.",
    bestFounderAnswer: "The round buys proof: retention, safety, distribution, and buyer conversion.",
    suggestedReference: "Ask & Use of Funds",
  },
  {
    id: "qa-082",
    category: "Government/Policy",
    difficulty: "Good",
    confidence: "Assumption",
    question: "What does a 90-day pilot produce?",
    whyInvestorAsks: "They want tangible outputs, not vague partnership talk.",
    shortAnswer: "A usage dashboard, risk log, farmer engagement metrics, partner feedback, and a scale/no-scale recommendation.",
    detailedAnswer: "The pilot should define target farmers, crops, languages, advisory modules, escalation, privacy controls, KPIs, and expected outputs before launch.",
    proof: "The pilot structure is a recommended implementation plan.",
    sourceIds: ["internal-assumptions"],
    whatNotToSay: "A pilot proves everything.",
    bestFounderAnswer: "A pilot is a disciplined test of usage, quality, safety, and buyer value.",
    suggestedReference: "Government / FPO Pilot Proposal",
  },
  {
    id: "qa-083",
    category: "Market",
    difficulty: "Tough",
    confidence: "High proof",
    question: "Is this a rural problem or national-scale problem?",
    whyInvestorAsks: "They want clarity on market framing.",
    shortAnswer: "It starts in rural agriculture but can become national-scale because farmer decision support is a broad infrastructure need.",
    detailedAnswer: "The market should be framed as smallholder-heavy and digitally reachable, but execution must start locally. National scale comes from repeatable crop-region-language expansion.",
    proof: "PM-KISAN scale supports the national backdrop; local wedge is a strategic assumption.",
    sourceIds: ["pm-kisan-toi", "internal-assumptions"],
    whatNotToSay: "We are national from day one.",
    bestFounderAnswer: "The problem is national; the execution is intentionally local first.",
    suggestedReference: "Market Opportunity; Roadmap",
  },
  {
    id: "qa-084",
    category: "Risk",
    difficulty: "Tough",
    confidence: "High proof",
    question: "What should investors not believe yet?",
    whyInvestorAsks: "They want to know whether the page separates proof from ambition.",
    shortAnswer: "They should not yet believe traction, retention, revenue, partnerships, yield impact, or disease accuracy unless new evidence is added.",
    detailedAnswer: "The strongest trust signal is honest labeling. The page should show market proof, product direction, and pilot plan while marking unsupported claims as assumptions or validation gaps.",
    proof: "The source analysis explicitly warns against fabricated traction or unsupported claims.",
    sourceIds: ["internal-assumptions"],
    whatNotToSay: "Everything is already proven.",
    bestFounderAnswer: "What is proven is the problem and category. What remains to prove is KisanAI's repeatable distribution, retention, safety, and revenue.",
    suggestedReference: "Data Proof Room; Risks & Mitigations",
  },
];

