import type { PitchSource } from "./types";

export const pitchSources: PitchSource[] = [
  {
    id: "kisanai-site",
    title: "KisanAI public site",
    url: "https://kishanai.strivio.world/",
    publisher: "KisanAI",
    year: "2026",
    confidence: "high",
  },
  {
    id: "founder-reddit",
    title: "Founder build note on KisanAI scope and stack",
    url: "https://www.reddit.com/r/alphaandbetausers/comments/1pcztvu/im_building_an_aipowered_agriculture_assistant/",
    publisher: "Reddit",
    year: "2026",
    confidence: "high",
  },
  {
    id: "toi-kisan-kapas",
    title: "Cotton farmers struggle with Kisan Kapas app",
    url: "https://timesofindia.indiatimes.com/city/nagpur/after-tariff-jolt-cotton-farmers-struggle-with-kisan-kapas-app/articleshow/124167831.cms",
    publisher: "Times of India",
    year: "2025",
    confidence: "medium",
  },
  {
    id: "toi-andhra-procurement",
    title: "CCI app failures push cotton farmers to private traders in Andhra Pradesh",
    url: "https://timesofindia.indiatimes.com/city/vijayawada/ccis-app-failures-push-cotton-farmers-to-private-traders-in-ap/articleshow/125139715.cms",
    publisher: "Times of India",
    year: "2025",
    confidence: "medium",
  },
  {
    id: "toi-onion-losses",
    title: "Onion crop loss over heavy rains leaves farmers in tears",
    url: "https://timesofindia.indiatimes.com/city/hubballi/onion-crop-loss-over-heavy-rains-leaves-farmers-in-tears/articleshow/123723965.cms",
    publisher: "Times of India",
    year: "2025",
    confidence: "medium",
  },
  {
    id: "toi-bharat-vistaar",
    title: "Agriculture ministry launches Bharat-VISTAAR",
    url: "https://timesofindia.indiatimes.com/india/agriculture-ministry-launches-bharat-vistaar-a-multilingual-ai-tool-for-digital-fam-advisories/articleshow/128472775.cms",
    publisher: "Times of India",
    year: "2026",
    confidence: "medium",
  },
  {
    id: "et-farmrise",
    title: "Bayer FarmRise reaches 5 million users",
    url: "https://m.economictimes.com/news/economy/agriculture/bayer-strengthens-its-phygital-connect-with-indian-farmers-as-farmrise-app-reaches-5-million-users/articleshow/131060228.cms",
    publisher: "Economic Times",
    year: "2026",
    confidence: "medium",
  },
  {
    id: "reuters-cropin",
    title: "Space data fuels India's farming innovation drive",
    url: "https://www.reuters.com/world/india/space-data-fuels-indias-farming-innovation-drive-2024-05-17/",
    publisher: "Reuters",
    year: "2024",
    confidence: "high",
  },
  {
    id: "pm-kisan-toi",
    title: "PM-KISAN instalment beneficiary scale",
    url: "https://timesofindia.indiatimes.com/city/varanasi/modi-to-release-20th-installment-of-pm-kisan-from-varanasi-today/articleshow/123049083.cms",
    publisher: "Times of India",
    year: "2025",
    confidence: "medium",
  },
  {
    id: "arxiv-disease-apps",
    title: "Review of plant disease detection mobile apps",
    url: "https://arxiv.org/abs/2208.02446",
    publisher: "arXiv",
    year: "2022",
    confidence: "medium",
  },
  {
    id: "arxiv-agri-qa",
    title: "Multilingual agricultural question-answering systems",
    url: "https://arxiv.org/abs/2508.03719",
    publisher: "arXiv",
    year: "2025",
    confidence: "medium",
  },
  {
    id: "arxiv-aiep",
    title: "Agricultural AI extension platform research",
    url: "https://arxiv.org/abs/2601.11537",
    publisher: "arXiv",
    year: "2026",
    confidence: "medium",
  },
  {
    id: "plantix-wiki",
    title: "Plantix overview",
    url: "https://en.wikipedia.org/wiki/Plantix",
    publisher: "Wikipedia",
    confidence: "medium",
  },
  {
    id: "wired-plantix",
    title: "Plantix and pesticide-selling concerns",
    url: "https://www.wired.com/story/plantix-app-agriculture-india-ai/",
    publisher: "Wired",
    confidence: "medium",
  },
  {
    id: "dehaat-wiki",
    title: "DeHaat overview",
    url: "https://en.wikipedia.org/wiki/DeHaat",
    publisher: "Wikipedia",
    confidence: "medium",
  },
  {
    id: "enam-wiki",
    title: "eNAM overview",
    url: "https://en.wikipedia.org/wiki/E-NAM",
    publisher: "Wikipedia",
    confidence: "medium",
  },
  {
    id: "aaqua-wiki",
    title: "aAQUA overview",
    url: "https://en.wikipedia.org/wiki/Aaqua",
    publisher: "Wikipedia",
    confidence: "medium",
  },
  {
    id: "kissanai-wiki",
    title: "Artificial intelligence in India, KissanAI reference",
    url: "https://en.wikipedia.org/wiki/Artificial_intelligence_in_India",
    publisher: "Wikipedia",
    confidence: "medium",
  },
  {
    id: "dpdp-wiki",
    title: "Digital Personal Data Protection Act, 2023 overview",
    url: "https://en.wikipedia.org/wiki/Digital_Personal_Data_Protection_Act%2C_2023",
    publisher: "Wikipedia",
    confidence: "medium",
  },
  {
    id: "startup-india-wiki",
    title: "Startup India overview",
    url: "https://en.wikipedia.org/wiki/Startup_India",
    publisher: "Wikipedia",
    confidence: "medium",
  },
  {
    id: "openai-pricing",
    title: "OpenAI API pricing",
    url: "https://openai.com/api/pricing/",
    publisher: "OpenAI",
    confidence: "medium",
  },
  {
    id: "cloudflare-r2-pricing",
    title: "Cloudflare R2 pricing",
    url: "https://developers.cloudflare.com/r2/pricing/",
    publisher: "Cloudflare",
    confidence: "medium",
  },
  {
    id: "neon-pricing",
    title: "Neon pricing",
    url: "https://neon.com/pricing",
    publisher: "Neon",
    confidence: "medium",
  },
  {
    id: "pinecone-pricing",
    title: "Pinecone pricing",
    url: "https://www.pinecone.io/pricing/",
    publisher: "Pinecone",
    confidence: "medium",
  },
  {
    id: "vercel-pricing",
    title: "Vercel pricing",
    url: "https://vercel.com/pricing",
    publisher: "Vercel",
    confidence: "medium",
  },
  {
    id: "internal-assumptions",
    title: "KisanAI pitch planning assumptions from supplied research files",
    publisher: "Internal pitch model",
    confidence: "low",
  },
];

export const sourceById = Object.fromEntries(
  pitchSources.map((source) => [source.id, source]),
) as Record<string, PitchSource>;

export function getSources(sourceIds: string[]) {
  return sourceIds.map((id) => sourceById[id]).filter(Boolean);
}

